# Generated by Django 5.0.3 on 2024-03-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_remove_bookedmovie_cost_remove_moviedate_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedmovie',
            name='booking',
            field=models.BooleanField(default=False),
        ),
    ]
