# Generated by Django 5.0.3 on 2024-03-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_bookedmovie_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedmovie',
            name='booking',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
