# Generated by Django 5.0.3 on 2024-03-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_bookedmovie_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedetails',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
